CREATE PROCEDURE [dbo].[PROC_INSERE_DATA_ID_DATA]
	@DATA_INI AS DATETIME, 
	@DATA_FIM AS DATETIME, 
	@DBNAME AS SYSNAME,
	@TABELA AS VARCHAR(100) = 'DIM_DATA',
	@HOJE DATETIME,
	@REGISTRO_1900 AS INT = 0
AS
/*
	PERCORRE OS DIAS ENTRE @DATA_INI E @DATA_FIM, PREENCHENDO DIFERSOS MODELOS DE DATA DIFERENTES
	OS MODELOS SAO USADOS CONFORME O CUBO E MONTADO
	
	PASSOS:
	1.DECLARA TABELA TEMPORARIA (@ EM FRENTE)
	2.INSERE DADOS NESSA TABELA TEMPORARIA 
	3.CASO EXISTA, DELETA TABELA NA DATABASE PASSADA EM @DBNAME
	4.FAZ UM INSERT INTO COM OS DADOS DA TEMPORARIA EM DIM_DATA OU NOME DA TABELA PASSADO
	
	OBS: 
	1. USA TABELA TEMPORARIA E SQL DINAMICO PORQUE PRECISA INSERIR EM OUTRA DATABASE
	2. COMEÇA UM ANO ANTES POIS PRECISA PROCESSAR OS DADOS AA
	3. UPDATES SÃO FEITOS NA TABELA TEMPORARIA POIS NÃO FOI POSSÍVEL RESOLVER OS PROBLEMAS NO PROCESSAMENTO NORMAL
*/

	/*PARA FAZER OS UPDATES AA*/
	
	DECLARE @DATA_INI_ORIGINAL DATETIME = @DATA_INI
	DECLARE @DATA_INI_ORIGINAL_STRING VARCHAR(10) = CONVERT(VARCHAR(10), @DATA_INI_ORIGINAL, 112)
	SET @DATA_INI = DATEADD(YEAR, -1, @DATA_INI)

	DECLARE @CRIA_REGISTRO_1900 BIT = 0
	
	IF(@REGISTRO_1900 <> 0)
	 SET @CRIA_REGISTRO_1900 = 1
	
	PRINT 'INICIO DE EXECUCAO DA PROCEDURE - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	SET LANGUAGE 'PORTUGUESE'
	
	IF OBJECT_ID('#DIM_DATA_TEMP') IS NOT NULL 
	DROP TABLE #DIM_DATA_TEMP 

	CREATE TABLE #DIM_DATA_TEMP( 
	ID_DATA											INT			NOT NULL PRIMARY KEY, /*20090101*/
	ANO												SMALLINT	NOT NULL, /*2009*/
	MES												TINYINT		NOT NULL, /*1*/
	MES_CHAR										VARCHAR(2)	NOT NULL, /*01*/
	MES_ANO_CHAR									VARCHAR(5)	NOT NULL, /*01/07*/
	MES_EXTENSO										VARCHAR(25)	NOT NULL, /*01 - JANEIRO*/
	MES_EXTENSO_ABREV								VARCHAR(3)	NOT NULL, /*Jan*/
	MES_ANO											VARCHAR(20)	NOT NULL, /*Janeiro/2009*/
	MES_ANO_MMMYY									VARCHAR(40)	NOT NULL, /*Jan/09*/
	MES_ANO_MMMYY_FILTRO							VARCHAR(50)	NOT NULL, /*Jan/09* com Mês Atual*/
	MES_ANO_ORDENACAO								INT			NOT NULL, /*200901*/
	QUINZENA										TINYINT		NOT NULL, /*1 ou 2*/
	QUINZENA_EXTENSO								VARCHAR(15)	NOT NULL, /*1 - Quinzena ou 2 - Quinzena*/
	SEMANA_MES										TINYINT		NOT NULL, /*1, 2, 3, 4 OU 5*/
	SEMANA_SEX_QUI_EXTENSA							VARCHAR(40)	NOT NULL, /*01 - 01/01/2009 A 05/01/2009 (de Sexta a Quinta - Usada no remanejo do varejo)*/
	SEMANA_SEX_QUI_ORDENACAO						INT			NOT NULL, /*1 ~ 999 Quebrando por semana*/
	SEMANA_QUA_TER_EXTENSA							VARCHAR(40)	NOT NULL, /*01 - 01/01/2009 A 05/01/2009 (de Quarta a Terça - Usada no remanejo do varejo)*/
	SEMANA_QUA_TER_ORDENACAO						INT			NOT NULL, /*1 ~ 999 Quebrando por semana*/
	SEMANA_DOM_SAB_EXTENSA							VARCHAR(40)	NOT NULL, /*01 - 01/01/2009 A 05/01/2009 (de Domingo a Sábado)*/
	SEMANA_DOM_SAB_ORDENACAO						INT			NOT NULL, /*1 ~ 999 Quebrando por semana*/
	SEMANA_SEG_DOM_EXTENSA							VARCHAR(40) NOT NULL, /*01 - 01/01/2009 A 05/01/2009 (de segunda a domingo)*/
	SEMANA_SEG_DOM_ORDENACAO						INT			NOT NULL, /*1 ~ 999 Quebrando por mes e semana*/
	SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA				VARCHAR(40) NOT NULL, /*01 - 01/01/2009 A 05/01/2009 (de segunda a domingo)*/
	SEMANA_SEG_DOM_QUEBRA_MES_ORDENACAO				INT			NULL,	  /*1 ~ 999 Quebrando por mes e semana*/
	SEMANA_ANO										SMALLINT    NOT NULL, /*1 ~ 52*/
	SEMANA_ANO_COMERCIAL							SMALLINT    NOT NULL, /*1 ~ 52 Começando na primeira segunda feira do ano*/
	SEMANA_ANO_SEG_DOM								SMALLINT    NOT NULL, /*1 ~ 52*/
	DIA_MES_DDMMM									VARCHAR(40) NOT NULL, /*01/Jan*/
	DIA_MES_ANO_DDMMMYY								VARCHAR(40) NOT NULL, /*01/Jan/12*/
	DIA_MES											TINYINT		NOT NULL, /*1 - 31*/
	DIA_COM_MES										VARCHAR(5)	NOT NULL, /*01/01*/
	DIA_COM_MES_ORDENACAO							INT			NOT NULL, /*0101*/
	DIA_SEMANA										TINYINT		NOT NULL, /*1 - 7*/
	DIA_SEMANA_SEG_DOM								TINYINT		NOT NULL, /*1 - 7*/
	DIA_SEMANA_EXTENSO								VARCHAR(15)	NOT NULL, /*Domingo - Sábado*/
	ULTIMO_DIA_MES									SMALLINT	NOT NULL, /*Último dia do mês (20130131) - 31*/
	ULTIMO_DIA_MES_COMPLETO							INT			NOT NULL, /*Último dia do mês 20130131*/
	PRIMEIRO_DIA_MES_COMPLETO						INT			NOT NULL, /*Último dia do mês 20130131*/
	DATA_DIA_SEMANA									VARCHAR(40) NOT NULL, /*01/01/2009 - SEGUNDA-FEIRA*/
	DATA_COMPLETA_EXTENSA							VARCHAR(40)	NOT NULL, /*Segunda-feira, 01 de Janeiro de 2009*/
	DIA_SEMANA_ABREV								VARCHAR(1)	NOT NULL, /*D S T Q Q S S*/
	DATA_FILTRO										DATE		NOT NULL, /*01/01/2009*/
	BIMESTRE										SMALLINT	NOT NULL,
	SEMESTRE										SMALLINT	NOT NULL,
	TRIMESTRE										SMALLINT	NOT NULL,
	ANO_REGRESSIVO									INT			NOT NULL, /*@HOJE - ANO*/
	SEMESTRE_REGRESSIVO								INT			NOT NULL, /*@HOJE - SEMESTRE*/
	TRIMESTRE_REGRESSIVO							INT			NOT NULL, /*@HOJE - TRIMESTRE*/
	MES_REGRESSIVO									INT			NOT NULL, /*@HOJE - MES*/
	MES_REGRESSIVO_EXTENSO							VARCHAR(50)	NOT NULL, /*@HOJE - MES*/
	MES_REGRESSIVO_ABERTO							INT			NOT NULL, /*@HOJE - MES*/
	SEMANA_SEX_QUI_REGRESSIVA						INT			NOT NULL, /*@HOJE - SEMANA*/	
	SEMANA_QUA_TER_REGRESSIVA						INT			NOT NULL, /*@HOJE - SEMANA*/
	SEMANA_DOM_SAB_REGRESSIVA						INT			NOT NULL, /*@HOJE - SEMANA*/
	SEMANA_SEG_DOM_REGRESSIVA						INT			NOT NULL, /*@HOJE - SEMANA*/
	SEMANA_SEG_DOM_QUEBRA_MES_REGRESSIVA			INT			NULL,	  /*@HOJE - SEMANA*/
	DIA_REGRESSIVO									INT			NOT NULL, /*@HOJE - DIA*/ 
	DIA_UTIL_REGRESSIVO								INT			NOT NULL,
	MES_UTIL_REGRESSIVO								INT			NOT NULL,
	ANO_UTIL_REGRESSIVO								INT			NOT NULL,
	ULTIMOS_180_DIAS								CHAR		NOT NULL, /*S - N*/
	DATA_COMISSOES									VARCHAR(15) NOT NULL, /*23/Abr - 24/Mai*/
	CALCULO_COMISSOES_REGRESSIVO					INT			NOT NULL, /*@HOJE - MES QUEBRADO POR DIA 24 DE CADA MES*/
	DATA_COTAS										VARCHAR(15)	NOT NULL, /*11/Agosto - 10/Setembro */
	COTAS_REGRESSIVO								INT			NOT NULL, /*@HOJE - MES QUEBRADO POR DIA 11 DE CADA MES  */
	ID_DATA_MA										INT			NOT NULL, /*PEGA O MESMO DIA NO MES ANTERIOR*/
	ID_DATA_AA										INT			NOT NULL, /*PEGA O MESMO DIA NO ANO ANTERIOR*/
	ID_DATA_AA_COMERCIAL							INT			NOT NULL, /*PEGA O MESMO DIA NO ANO ANTERIOR MAS USA O DIA DA SEMANA COMO REFERÊNCIA*/
	/*COMERCIAIS*/	   
	ANO_COMERCIAL									INT			NULL, /*2017*/
	ANO_COMERCIAL_REGRESSIVO						INT			NULL, /*1,0,-1*/
	MES_COMERCIAL									INT			NULL, /*201701*/
	MES_COMERCIAL_REGRESSIVO						INT			NULL, /*1,0,-1*/
	MES_COMERCIAL_ORDENACAO							INT			NULL,
	MES_ANO_COMERCIAL								VARCHAR(50) NULL, /*JANEIRO/2017*/
	MES_ANO_MMMYY_COMERCIAL							VARCHAR(50) NULL, /*Jan/2017*/
	MES_COMERCIAL_EXTENSO							VARCHAR(50) NULL, /*01 - JANEIRO*/
	MES_COMERCIAL_NUMERICO							INT			NULL, /*1*/
	TRIMESTRE_COMERCIAL_NUMERICO					INT			NULL, /*1*/
	TRIMESTRE_COMERCIAL								VARCHAR(50) NULL, /*Jan/2017*/
	TRIMESTRE_COMERCIAL_REGRESSIVO					INT			NULL, /*1*/
	SEMANA_COMERCIAL								VARCHAR(50) NULL, /*W1 2017*/
	SEMANA_COMERCIAL_REGRESSIVA						INT			NULL, /*1,0,-1*/
	SEMANA_COMERCIAL_REMANEJO    					VARCHAR(50) NULL, /*W2 2017 -> PEGA A SEMANA DA FRENTE. REMANEJO ESTÁ SEMPRE OLHANDO PRO PASSADO*/
	SEMANA_COMERCIAL_REMANEJO_QUA_TER				VARCHAR(50) NULL, /*W2 2017 -> PEGA A SEMANA DA FRENTE. REMANEJO ESTÁ SEMPRE OLHANDO PRO PASSADO*/
	SEMANA_COMERCIAL_NUMERICA						INT			NULL, /*1 ~ 54*/
	MES_COMERCIAL_REGRESSIVO_QUEBRA_ANO				VARCHAR(1) NOT NULL DEFAULT 'N'
   )
	
	DECLARE @QTD_DIAS INT 
	SET @DATA_FIM = DATEADD(DAY, 1, @DATA_FIM)
	SET @QTD_DIAS = datediff(day, @DATA_INI, @DATA_FIM)
	
	IF(@CRIA_REGISTRO_1900 = 1)
		SET @QTD_DIAS = @QTD_DIAS + 1
	
	BEGIN
	   PRINT 'ÍNÍCIO DO PROCESSAMENTO - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)

	   DECLARE @CNT INT = 0
	   DECLARE @SEMANAS_INICIO_SEG INT
	   DECLARE @SEMANAS_INICIO_DOM INT
	   DECLARE @DATA_DIMENSAO DATETIME 
	   DECLARE @SEMESTRE_REG INT
	   DECLARE @FIM_SEMANA_DOM_SAB DATETIME
	   DECLARE @FIM_SEMANA_SEG_DOM_QUEBRA_MES DATETIME
	   DECLARE @FIM_SEMANA_SEG_DOM DATETIME
	   DECLARE @SEMANA_COMERCIAL_EXTENSA VARCHAR(40)
	   
	   /*VARIAVEIS DO INSERT*/
	   DECLARE @DIA_ATUAL_NUMERO INT = DATEPART(DAY, @HOJE)     /*****************************/
	   DECLARE @MES_REGRESSIVO_ABERTO INT = 0					/* PARA MES ABERTO REGRESSIVO*/
	   DECLARE @MES_REGRESSIVO INT = 0							/*****************************/
	   DECLARE @MES_REGRESSIVO_DATA DATETIME					/*****************************/
	   DECLARE @MES_REGRESSIVO_ABRETO_DIF INT = 0				/*****************************/
	   DECLARE @CALCULO_COMISSOES_REGRESSIVO_DIF INT = 0
	   DECLARE @CALCULO_COMISSOES_REGRESSIVO INT = 0
	   DECLARE @DATA_COTAS_REGRESSIVO_DIF INT = 0
	   DECLARE @DATA_COTAS_REGRESSIVO INT = 0
	   DECLARE @DATA_COMPLETA VARCHAR(40)
	   DECLARE @DIA_SEMANA_EXTENSO VARCHAR(15)
	   DECLARE @DIA_SEMANA TINYINT
	   DECLARE @SEMANA_MES TINYINT = 0
	   DECLARE @SEMANA_MES_AUX NUMERIC(18,4)
	   DECLARE @SEMANA_SEX_QUI_EXTENSA VARCHAR(40)
	   DECLARE @SEMANA_SEX_QUI_ORDENACAO INT = 0
	   DECLARE @SEMANA_QUA_TER_EXTENSA VARCHAR(40)
	   DECLARE @SEMANA_QUA_TER_ORDENACAO INT = 0
	   DECLARE @SEMANA_DOM_SAB_EXTENSA VARCHAR(40)
	   DECLARE @SEMANA_DOM_SAB_ORDENACAO INT = 0
	   DECLARE @SEMANA_SEG_DOM_EXTENSA VARCHAR(40)
	   DECLARE @SEMANA_SEG_DOM_ORDENACAO INT = 0
	   DECLARE @SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA VARCHAR(40)
	   DECLARE @MES_ANO_MMMYY VARCHAR(6)
	   DECLARE @DIA_MES_DDMMM VARCHAR(6)
	   DECLARE @PRIMEIRO_DIA_MES_COMPLETO INT
	   DECLARE @MES_RESUMIDO VARCHAR(3)
	   DECLARE @MES_RESUMIDO_ANTE VARCHAR(3)
	   DECLARE @MES_RESUMIDO_PROX VARCHAR(3)
	   DECLARE @QUINZENA VARCHAR(1)
	   DECLARE @DIA_MES TINYINT
	   DECLARE @MES VARCHAR(10)
	   DECLARE @MES_NUMERO TINYINT
	   DECLARE @ANO SMALLINT
	   DECLARE @ANO_ANTERIOR SMALLINT
	   DECLARE @SEMANA_ANO_COMERCIAL SMALLINT
	   DECLARE @SEMANA_ANO_COMERCIAL_TROCOU_ANO BIT
	   DECLARE @DIA_UTIL_REGRESSIVO INT
	   DECLARE @MES_UTIL_REGRESSIVO INT
	   DECLARE @ANO_REGRESSIVO INT
	   DECLARE @ANO_UTIL_REGRESSIVO INT
	   DECLARE @DATA_COMISSOES VARCHAR(15)
	   DECLARE @DATA_COTAS VARCHAR(15)	   

	   SET @CNT = 0		
		
	   WHILE (@CNT < @QTD_DIAS)
	   BEGIN
	   
			IF(@CNT = 0)
			BEGIN
				IF(@CRIA_REGISTRO_1900 = 1)
					SET @DATA_DIMENSAO =  CONVERT(DATETIME, CONVERT(VARCHAR(10), @REGISTRO_1900), 103)
				ELSE
					SET @DATA_DIMENSAO = @DATA_INI
			

				SET @MES_REGRESSIVO_ABERTO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE)))

				SET @CALCULO_COMISSOES_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE))) + 1
				
				IF((DATEPART(DAY, @HOJE)) <= 10)
					SET @DATA_COTAS_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE)))-1
				ELSE 
					SET @DATA_COTAS_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE)))

				SET @MES_REGRESSIVO_DATA = @DATA_DIMENSAO
				
						
				DECLARE @INICIO_CONTAGEM_SEG DATETIME
				DECLARE @INICIO_CONTAGEM_SEX DATETIME
				DECLARE @FIM_CONTAGEM_SEG DATETIME
				
				IF(DATEPART(WEEKDAY, @HOJE) >= 2)
				BEGIN
					SET @FIM_CONTAGEM_SEG = DATEADD(DAY, 8 - DATEPART(WEEKDAY, @HOJE), @HOJE)	
				END
				IF(DATEPART(WEEKDAY, @HOJE) = 1)
				BEGIN
					SET @FIM_CONTAGEM_SEG = DATEADD(DAY, 1, @HOJE)	
				END
				ELSE
				BEGIN
					SET @FIM_CONTAGEM_SEG = @HOJE
				END

				DECLARE @INICIO_CONTAGEM_DOM DATETIME
				DECLARE @FIM_CONTAGEM_DOM DATETIME

				IF(DATEPART(WEEKDAY, @HOJE) <> 1)
				BEGIN
					SET @FIM_CONTAGEM_DOM = DATEADD(DAY, -(DATEPART(WEEKDAY, @HOJE)-1), @HOJE)	
				END
				ELSE
					SET @FIM_CONTAGEM_DOM = DATEADD(DAY, -7, @HOJE)

				IF(DATEPART(WEEKDAY, @DATA_DIMENSAO) <> 1)
				BEGIN
					SET @INICIO_CONTAGEM_DOM = DATEADD(DAY, 8 - DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO) 

					/*EXISTE UMA SEMANA EM ABERTO ANTES DO PRIMEIRO DOMINGO*/

					SET @SEMANAS_INICIO_DOM = (DATEDIFF(DAY, @INICIO_CONTAGEM_DOM, @FIM_CONTAGEM_DOM) / 7) + 1 
				END
				ELSE
				BEGIN
					SET @INICIO_CONTAGEM_DOM = @DATA_DIMENSAO

					SET @SEMANAS_INICIO_DOM = (DATEDIFF(DAY, @INICIO_CONTAGEM_DOM, @FIM_CONTAGEM_DOM) / 7)
				END

				IF(DATEPART(WEEKDAY, @DATA_DIMENSAO) <> 2)
				BEGIN
					
					IF(DATEPART(WEEKDAY, @DATA_DIMENSAO) = 5)
					BEGIN
						SET @INICIO_CONTAGEM_SEX = DATEADD(DAY, 1, @DATA_DIMENSAO)
					END
					ELSE
					BEGIN
						/*SETA O INICIO DA CONTAGEM PARA A PROXIMA SEXTA*/
						SET @INICIO_CONTAGEM_SEX = DATEADD(DAY, 6 - DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO) + 1
					END
					
					IF(DATEPART(WEEKDAY, @DATA_DIMENSAO) = 1)
					BEGIN
						SET @INICIO_CONTAGEM_SEG = DATEADD(DAY, 1, @DATA_DIMENSAO)
					END
					ELSE
					BEGIN
						/*SETA O INICIO DA CONTAGEM PARA A PROXIMA SEGUNDA*/
						SET @INICIO_CONTAGEM_SEG = DATEADD(DAY, 8 - DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO) + 1
					END

					/*ADICIONA UM DIA NA DIFERENÇA DOS DIAS, PROBLEMA DO SQL SERVER QUE NAO CONTA O DIA INTEIRO*/
					/*EXISTE UMA SEMANA EM ABERTO ANTES DA PRIMEIRA SEGUNDA, POR ISSO ADICIONA UMA SEMANA AO FIM DO CALCULO*/
					SET @SEMANAS_INICIO_SEG = ((DATEDIFF(DAY, @INICIO_CONTAGEM_SEG, @FIM_CONTAGEM_DOM) + 1) / 7) + 1


				END
				ELSE
				BEGIN 
				
					SET @INICIO_CONTAGEM_SEX = @DATA_DIMENSAO
					SET @INICIO_CONTAGEM_SEG = @DATA_DIMENSAO
					SET @SEMANAS_INICIO_SEG = ((DATEDIFF(DAY, @INICIO_CONTAGEM_SEG, @FIM_CONTAGEM_DOM) + 1) / 7)

					
				END

				SET @ANO_ANTERIOR = DATEPART(YEAR, CONVERT(DATETIME,@DATA_DIMENSAO))
				SET @SEMANA_ANO_COMERCIAL = 0
				SET @SEMANA_ANO_COMERCIAL_TROCOU_ANO = 1
			END
			 
			
			SET @ANO_REGRESSIVO = DATEDIFF(YEAR, @DATA_DIMENSAO, @HOJE)
			SET @MES_NUMERO = DATEPART(MONTH, @DATA_DIMENSAO)
			SET @ANO = DATEPART(YEAR, CONVERT(DATETIME,@DATA_DIMENSAO))
			SET @DIA_SEMANA_EXTENSO = rtrim(UPPER(SUBSTRING(DATENAME(WEEKDAY,@DATA_DIMENSAO),1,1))+SUBSTRING(DATENAME(WEEKDAY,@DATA_DIMENSAO),2, LEN(DATENAME(WEEKDAY,@DATA_DIMENSAO))))	
			SET @MES = UPPER(SUBSTRING(DATENAME(MONTH, @DATA_DIMENSAO),1,1))+SUBSTRING(DATENAME(MONTH, @DATA_DIMENSAO), 2, LEN(DATENAME(MONTH,@DATA_DIMENSAO)))
			SET @MES_RESUMIDO = SUBSTRING(@MES, 1,3)
			SET @MES_RESUMIDO_PROX = SUBSTRING(UPPER(SUBSTRING(DATENAME(MONTH, DATEADD(MONTH, 1, @DATA_DIMENSAO)),1,1))+SUBSTRING(DATENAME(MONTH, DATEADD(MONTH, 1, @DATA_DIMENSAO)), 2, LEN(DATENAME(MONTH,DATEADD(MONTH, 1, @DATA_DIMENSAO)))), 1,3)
			SET @MES_RESUMIDO_ANTE = SUBSTRING(UPPER(SUBSTRING(DATENAME(MONTH, DATEADD(MONTH, -1, @DATA_DIMENSAO)),1,1))+SUBSTRING(DATENAME(MONTH, DATEADD(MONTH, -1, @DATA_DIMENSAO)), 2, LEN(DATENAME(MONTH,DATEADD(MONTH, -1, @DATA_DIMENSAO)))), 1,3)
			SET @DIA_MES = DATEPART(DAY, @DATA_DIMENSAO)
			SET @MES_ANO_MMMYY = @MES_RESUMIDO + '/' +  SUBSTRING(CONVERT(VARCHAR(4), @ANO), 3, 2)
			SET @DIA_MES_DDMMM =  RIGHT('0' + CONVERT(VARCHAR(2),DATEPART(DAY, @DATA_DIMENSAO)), 2)+ '/' + @MES_RESUMIDO 
			SET @QUINZENA = CASE WHEN @DIA_MES <= 15 THEN '1' ELSE '2' END 	 
		
		
			IF (DATEPART(DAY, @DATA_DIMENSAO) < 24)
		  		SET @DATA_COMISSOES = '24/'+@MES_RESUMIDO_ANTE + ' - 23/'+ @MES_RESUMIDO
		  	ELSE
		  		SET @DATA_COMISSOES = '24/'+@MES_RESUMIDO + ' - 23/'+ @MES_RESUMIDO_PROX
		  		
		  		
			IF (DATEPART(DAY, @DATA_DIMENSAO) = 24)
			BEGIN
		  		SET @CALCULO_COMISSOES_REGRESSIVO_DIF = @CALCULO_COMISSOES_REGRESSIVO_DIF -1
			END

			IF (DATEPART(DAY, @DATA_DIMENSAO) < 11)
		  		SET @DATA_COTAS = '11/'+@MES_RESUMIDO_ANTE + ' - 10/'+ @MES_RESUMIDO
		  	ELSE
		  		SET @DATA_COTAS = '11/'+@MES_RESUMIDO + ' - 10/'+ @MES_RESUMIDO_PROX
		  		
		  		
			IF (DATEPART(DAY, @DATA_DIMENSAO) = 11)
			BEGIN
		  		SET @DATA_COTAS_REGRESSIVO_DIF = @DATA_COTAS_REGRESSIVO_DIF -1
			END
		
			IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'QUARTA-FEIRA' OR @CNT = 0)
			BEGIN
				
				SET @SEMANA_QUA_TER_EXTENSA = SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),9,2) + ' a ' + SUBSTRING(CONVERT(VARCHAR(10),DATEADD(DAY, 6, @DATA_DIMENSAO),103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),DATEADD(DAY, 6, @DATA_DIMENSAO),103),9,2)
				
				IF(@CNT <> 0)
					SET @SEMANA_QUA_TER_ORDENACAO = @SEMANA_QUA_TER_ORDENACAO + 1
			END

			
			IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'SEXTA-FEIRA' OR @CNT = 0)
			BEGIN
				
				SET @SEMANA_SEX_QUI_EXTENSA = SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),9,2) + ' a ' + SUBSTRING(CONVERT(VARCHAR(10),DATEADD(DAY, 6, @DATA_DIMENSAO),103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),DATEADD(DAY, 6, @DATA_DIMENSAO),103),9,2)
				
				IF(@CNT <> 0)
					SET @SEMANA_SEX_QUI_ORDENACAO = @SEMANA_SEX_QUI_ORDENACAO + 1
			END
			

			IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'DOMINGO' OR @CNT = 0)
			BEGIN
				SET @FIM_SEMANA_DOM_SAB = DATEADD(DAY, 7-DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO)
				SET @SEMANA_DOM_SAB_EXTENSA = SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),9,2) + ' a ' + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_DOM_SAB,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_DOM_SAB,103),9,2)
				
				IF(@CNT <> 0)
				BEGIN
					SET @SEMANAS_INICIO_DOM = @SEMANAS_INICIO_DOM - 1
					SET @SEMANA_DOM_SAB_ORDENACAO = @SEMANA_DOM_SAB_ORDENACAO + 1
				END
			END
				
			IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'SEGUNDA-FEIRA' OR @CNT = 0)
			BEGIN
				SET @FIM_SEMANA_SEG_DOM = DATEADD(DAY, 8-DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO)
				SET @SEMANA_SEG_DOM_EXTENSA = SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),9,2) + ' a ' + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_SEG_DOM,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_SEG_DOM,103),9,2)
				
				IF(@CNT <> 0)
				BEGIN
					SET @SEMANAS_INICIO_SEG = @SEMANAS_INICIO_SEG - 1
					SET @SEMANA_SEG_DOM_ORDENACAO = @SEMANA_SEG_DOM_ORDENACAO + 1
				END
			END
				
				
			IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'SEGUNDA-FEIRA' OR @CNT = 0 OR @DIA_MES = 1)
			BEGIN
				
				IF((DAY(DATEADD(month,DATEDIFF(month,0,@DATA_DIMENSAO)+1,-1)) - @DIA_MES) < 7)
					SET @FIM_SEMANA_SEG_DOM_QUEBRA_MES = DATEADD(DAY, (DAY(DATEADD(month,DATEDIFF(month,0,@DATA_DIMENSAO)+1,-1)) - @DIA_MES), @DATA_DIMENSAO)
				ELSE 
				BEGIN 
					IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'DOMINGO')
						SET @FIM_SEMANA_SEG_DOM_QUEBRA_MES = @DATA_DIMENSAO
					ELSE
						SET @FIM_SEMANA_SEG_DOM_QUEBRA_MES = DATEADD(DAY, 8-DATEPART(WEEKDAY, @DATA_DIMENSAO), @DATA_DIMENSAO)
				END
								
				SET @SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA = SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@DATA_DIMENSAO,103),9,2) + ' a ' + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_SEG_DOM_QUEBRA_MES,103),0,7) + SUBSTRING(CONVERT(VARCHAR(10),@FIM_SEMANA_SEG_DOM_QUEBRA_MES,103),9,2)
				
			END
			
			IF(DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE) % 6 > 0)
				SET @SEMESTRE_REG = (DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE) / 6) + 1
			ELSE 
				SET @SEMESTRE_REG = DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE) / 6
			

			SET @DATA_COMPLETA = rtrim(@DIA_SEMANA_EXTENSO
				+ ', ' + RIGHT(REPLICATE('0',2) + CAST(DATEPART(DAY, @DATA_DIMENSAO) AS VARCHAR(2)),2) 
				+ ' de ' + UPPER(SUBSTRING(DATENAME(MONTH,@DATA_DIMENSAO),1,1))+SUBSTRING(DATENAME(MONTH,@DATA_DIMENSAO),2, LEN(DATENAME(MONTH,@DATA_DIMENSAO)))
				+ ' de ' + CONVERT(VARCHAR(4), DATEPART(YEAR,@DATA_DIMENSAO)))	
				
	      IF (DATEPART(DAY, @HOJE) = 1)
	         SET @MES_UTIL_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE))) - 1
	      ELSE IF (DATEPART(DAY, @HOJE) = 2 AND DATEPART(WEEKDAY, @HOJE) = 2)
	         SET @MES_UTIL_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE))) - 1
	      ELSE
	         SET @MES_UTIL_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE)))
	         
	      SET @DIA_UTIL_REGRESSIVO = 
	         CASE
	            WHEN (rtrim(CONVERT(VARCHAR(10), DATEDIFF(DAY, @DATA_DIMENSAO, @HOJE))) <= 0) THEN rtrim(CONVERT(VARCHAR(10), DATEDIFF(DAY, @DATA_DIMENSAO, @HOJE)))
	            WHEN ((DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO))) = 1) THEN 9999
	            WHEN ((DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO))) = 7) THEN 9999
	            WHEN ((DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO))) = 6) THEN (rtrim(CONVERT(VARCHAR(10), DATEDIFF(DAY, @DATA_DIMENSAO, @HOJE))) -2)
	            ELSE rtrim(CONVERT(VARCHAR(10), DATEDIFF(DAY, @DATA_DIMENSAO, @HOJE)))
	         END
		  
		  IF (DATEPART(MONTH, @HOJE) = 1)
			SET @ANO_UTIL_REGRESSIVO = @ANO_REGRESSIVO - 1
		  ELSE
			SET @ANO_UTIL_REGRESSIVO = @ANO_REGRESSIVO
		  
		  SET @PRIMEIRO_DIA_MES_COMPLETO = CONVERT(VARCHAR(4), @ANO)+RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2)+'01'
		  
		  IF(@PRIMEIRO_DIA_MES_COMPLETO = CONVERT(VARCHAR(10), @DATA_DIMENSAO, 112))
		  BEGIN 
			SET @SEMANA_MES = 1
		  END
		  ELSE IF (UPPER(DATENAME(WEEKDAY,@DATA_DIMENSAO)) = 'DOMINGO')
		  BEGIN
			SET @SEMANA_MES = @SEMANA_MES +1
		  END


		  /*SET @SEMANA_MES_AUX = (((CONVERT(VARCHAR(10), @DATA_DIMENSAO, 112) - @PRIMEIRO_DIA_MES_COMPLETO)+1) / 7.0)
		  
		  IF((@SEMANA_MES_AUX - CAST(@SEMANA_MES_AUX AS TINYINT)) > 0 OR @SEMANA_MES_AUX = 0)
		  BEGIN
			SET @SEMANA_MES = (CAST(@SEMANA_MES_AUX AS TINYINT) + 1)
		  END
		  ELSE 
		  BEGIN
			SET @SEMANA_MES = CAST(@SEMANA_MES_AUX AS TINYINT)
		  END*/


		  IF(@ANO_ANTERIOR <> @ANO)
		  BEGIN

			SET @SEMANA_ANO_COMERCIAL = 0 /* PARA DEIXAR OS PRIMEIROS DIAS DE ANOS QUE NÃO COMEÇAM NA SEGUNDA COMO 0*/
		    SET @SEMANA_ANO_COMERCIAL_TROCOU_ANO = 1
		  END

		  PRINT @SEMANA_ANO_COMERCIAL_TROCOU_ANO
		  IF(@SEMANA_ANO_COMERCIAL_TROCOU_ANO = 1 AND DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) = 2)
		  BEGIN
			SET @SEMANA_ANO_COMERCIAL = 1
			SET @SEMANA_ANO_COMERCIAL_TROCOU_ANO = 0
		  END
		  ELSE IF(@SEMANA_ANO_COMERCIAL_TROCOU_ANO = 0 AND DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) = 2)
		  BEGIN
			SET @SEMANA_ANO_COMERCIAL = @SEMANA_ANO_COMERCIAL + 1
		  END

		  SET @MES_REGRESSIVO = rtrim(CONVERT(VARCHAR(10), DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE)))

print '---'
print @HOJE
print @DATA_DIMENSAO
print '---'

	INSERT INTO #DIM_DATA_TEMP(ID_DATA, ANO, MES, MES_CHAR, MES_ANO_CHAR, MES_EXTENSO, MES_EXTENSO_ABREV, MES_ANO, MES_ANO_MMMYY, MES_ANO_MMMYY_FILTRO, MES_ANO_ORDENACAO,
							 DIA_MES_DDMMM, DIA_MES_ANO_DDMMMYY, DIA_SEMANA, DIA_SEMANA_SEG_DOM, DIA_SEMANA_EXTENSO, ULTIMO_DIA_MES, ULTIMO_DIA_MES_COMPLETO, PRIMEIRO_DIA_MES_COMPLETO, DIA_MES, DIA_COM_MES, DIA_COM_MES_ORDENACAO,					
						     QUINZENA, QUINZENA_EXTENSO, SEMANA_MES, SEMANA_SEX_QUI_EXTENSA, SEMANA_SEX_QUI_ORDENACAO, SEMANA_QUA_TER_EXTENSA, SEMANA_QUA_TER_ORDENACAO, SEMANA_DOM_SAB_EXTENSA, SEMANA_DOM_SAB_ORDENACAO, SEMANA_SEG_DOM_EXTENSA, SEMANA_SEG_DOM_ORDENACAO, 
							 SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA, SEMANA_SEG_DOM_QUEBRA_MES_ORDENACAO, SEMANA_ANO, SEMANA_ANO_COMERCIAL, SEMANA_ANO_SEG_DOM, DATA_DIA_SEMANA, DATA_COMPLETA_EXTENSA, DIA_SEMANA_ABREV, DATA_FILTRO,		
							 BIMESTRE, SEMESTRE, TRIMESTRE,	DIA_REGRESSIVO, SEMANA_SEX_QUI_REGRESSIVA, SEMANA_QUA_TER_REGRESSIVA, SEMANA_DOM_SAB_REGRESSIVA, SEMANA_SEG_DOM_REGRESSIVA, SEMANA_SEG_DOM_QUEBRA_MES_REGRESSIVA, MES_REGRESSIVO, MES_REGRESSIVO_EXTENSO, MES_REGRESSIVO_ABERTO, 
							 TRIMESTRE_REGRESSIVO, SEMESTRE_REGRESSIVO, ANO_REGRESSIVO, DIA_UTIL_REGRESSIVO, MES_UTIL_REGRESSIVO, ANO_UTIL_REGRESSIVO, ULTIMOS_180_DIAS, DATA_COMISSOES, CALCULO_COMISSOES_REGRESSIVO, DATA_COTAS, 
							 COTAS_REGRESSIVO, ID_DATA_MA, ID_DATA_AA, ID_DATA_AA_COMERCIAL)
/*ID_DATA*/						        VALUES (CONVERT(VARCHAR(10), @DATA_DIMENSAO, 112)
/*ANO*/       									,@ANO
/*MES*/ 										,@MES_NUMERO			
/*MES_CHAR*/ 									,RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2)		
/*MES_ANO_CHAR*/ 								,RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2) +'/' +  SUBSTRING(CONVERT(VARCHAR(4), @ANO), 3, 2)
/*MES_EXTENSO*/									,@MES
/*MES_EXTENSO_ABREV*/							,@MES_RESUMIDO
/*MES_ANO*/										,@MES + '/'+CONVERT(VARCHAR(4), @ANO)
/*MES_ANO_MMMYY*/								,@MES_ANO_MMMYY
/*MES_ANO_MMMYY_FILTRO*/						,CASE WHEN @MES_REGRESSIVO = 0 THEN 'Mes Atual' ELSE @MES_ANO_MMMYY END
/*MES_ANO_ORDENACAO*/							,CONVERT(INT, CONVERT(VARCHAR(4), @ANO)+RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2))
/*DIA_MES_DDMMM*/								,@DIA_MES_DDMMM
/*DIA_MES_ANO_DDMMMYY*/							,@DIA_MES_DDMMM + '/' +  SUBSTRING(CONVERT(VARCHAR(4), @ANO), 3, 2)
/*DIA_SEMANA*/									,DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO))
/*DIA_SEMANA_SEG_DOM*/							,CASE WHEN DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) = 1 THEN 7 ELSE DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) -1 END
/*DIA_SEMANA_EXTENSO*/							,@DIA_SEMANA_EXTENSO
/*ULTIMO_DIA_MES*/								,DATEPART(DAY, DATEADD(month,DATEDIFF(month,0,@DATA_DIMENSAO)+1,-1))
/*ULTIMO_DIA_MES_COMPLETO*/						,CONVERT(VARCHAR(10), DATEADD(month,DATEDIFF(month,0,@DATA_DIMENSAO)+1,-1), 112)
/*PRIMEIRO_DIA_MES_COMPLETO*/					,@PRIMEIRO_DIA_MES_COMPLETO
/*DIA_MES*/										,@DIA_MES
/*DIA_COM_MES*/									,RIGHT('0' + CONVERT(VARCHAR(2), @DIA_MES), 2)+'/'+RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2)
/*DIA_COM_MES_ORDENACAO*/						,CONVERT(INT, RIGHT('0' + CONVERT(VARCHAR(2), @MES_NUMERO), 2)+RIGHT('0' + CONVERT(VARCHAR(2), @DIA_MES), 2))
/*QUINZENA*/									,@QUINZENA
/*QUINZENA_EXTENSO*/							,@QUINZENA + ' - QUINZENA'
/*SEMANA_MES*/									,@SEMANA_MES
/*SEMANA_SEX_QUI_EXTENSA*/						,@SEMANA_SEX_QUI_EXTENSA
/*SEMANA_SEX_QUI_ORDENACAO*/					,@SEMANA_SEX_QUI_ORDENACAO
/*SEMANA_QUA_TER_EXTENSA*/						,@SEMANA_QUA_TER_EXTENSA
/*SEMANA_QUA_TER_ORDENACAO*/					,@SEMANA_QUA_TER_ORDENACAO
/*SEMANA_DOM_SAB_EXTENSA*/						,@SEMANA_DOM_SAB_EXTENSA
/*SEMANA_DOM_SAB_ORDENACAO*/					,@SEMANA_DOM_SAB_ORDENACAO
/*SEMANA_SEG_DOM_EXTENSA*/						,@SEMANA_SEG_DOM_EXTENSA
/*SEMANA_SEG_DOM_ORDENACAO*/					,@SEMANA_SEG_DOM_ORDENACAO
/*SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA*/			,@SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA
/*SEMANA_SEG_DOM_QUEBRA_MES_ORDENACAO*/			,null
/*SEMANA_ANO*/									,DATEPART(wk, @DATA_DIMENSAO)
/*SEMANA_ANO_COMERCIAL*/						,@SEMANA_ANO_COMERCIAL
/*SEMANA_ANO_SEG_DOM*/							,CASE WHEN DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) = 1  AND DATEPART(wk, @DATA_DIMENSAO) = 1 THEN DATEPART(wk, DATEADD(DAY, -1, @DATA_DIMENSAO)) WHEN DATEPART(WEEKDAY, CONVERT(DATETIME, @DATA_DIMENSAO)) = 1 THEN DATEPART(wk, @DATA_DIMENSAO) -1 ELSE DATEPART(wk, @DATA_DIMENSAO) END
/*DATA_DIA_SEMANA*/								,CONVERT(VARCHAR(10), @DATA_DIMENSAO, 103) + ' - ' + UPPER(DATENAME(WEEKDAY, @DATA_DIMENSAO))	
/*DATA_COMPLETA_EXT.*/							,@DATA_COMPLETA
/*DIA_SEMANA_ABREV*/							,SUBSTRING(@DATA_COMPLETA,1,1)
/*DATA_FILTRO*/									,@DATA_DIMENSAO
/*BIMESTRE*/									,CASE WHEN @MES_NUMERO <= 2 THEN 1 WHEN @MES_NUMERO <= 4 THEN 2 WHEN @MES_NUMERO <= 6 THEN 3 WHEN @MES_NUMERO <= 8 THEN 4 WHEN @MES_NUMERO <= 10 THEN 5 ELSE 6 END 
/*SEMESTRE*/									,CASE WHEN @MES_NUMERO <= 6 THEN 1 ELSE 2 END 
/*TRIMESTRE*/									,CASE WHEN @MES_NUMERO <= 3 THEN 1 WHEN @MES_NUMERO <= 6 THEN 2 WHEN @MES_NUMERO <= 9 THEN 3 ELSE 4 END
/*DIA_REGRESSIVO*/								,rtrim(CONVERT(VARCHAR(10), DATEDIFF(DAY, @DATA_DIMENSAO, @HOJE)))
/*SEMANA_SEX_QUI_REGRESSIVA*/					,CASE WHEN (@CRIA_REGISTRO_1900 = 1 AND @DATA_DIMENSAO =  CONVERT(DATETIME, CONVERT(VARCHAR(10), @REGISTRO_1900), 103)) THEN 99999 ELSE DBO.FUNC_DESCOBRE_SEMANA_REGRESSIVA(@HOJE, @DATA_DIMENSAO, 6, 5) END
/*SEMANA_QUA_TER_REGRESSIVA*/					,CASE WHEN (@CRIA_REGISTRO_1900 = 1 AND @DATA_DIMENSAO =  CONVERT(DATETIME, CONVERT(VARCHAR(10), @REGISTRO_1900), 103)) THEN 99999 ELSE DBO.FUNC_DESCOBRE_SEMANA_REGRESSIVA(@HOJE, @DATA_DIMENSAO, 4, 3) END
/*SEMANA_DOM_SAB_REGRESSIVA*/					,@SEMANAS_INICIO_DOM
/*SEMANA_SEG_DOM_REGRESSIVA*/					,@SEMANAS_INICIO_SEG
/*SEMANA_SEG_DOM_QUEBRA_MES_REGRESSIVA*/		,null
/*MES_REGRESSIVO*/								,@MES_REGRESSIVO
/*MES_REGRESSIVO_EXTENSO*/					    ,CASE WHEN @MES_REGRESSIVO = 0 THEN 'Mes Atual' WHEN @MES_REGRESSIVO = 1 THEN 'Mes Passado' WHEN @MES_REGRESSIVO = -1 THEN 'Proximo Mes' WHEN @MES_REGRESSIVO > 1 THEN CAST(@MES_REGRESSIVO AS VARCHAR(10)) + ' Meses Atras'  WHEN @MES_REGRESSIVO < -1 THEN CAST(ABS(@MES_REGRESSIVO) AS VARCHAR(10)) + ' Meses no Futuro'  END
/*MES_REGRESSIVO_ABERTO*/						,@MES_REGRESSIVO_ABERTO+@MES_REGRESSIVO_ABRETO_DIF
/*TRIMESTRE_REGRE.*/							,rtrim(CONVERT(VARCHAR(10), DATEDIFF(QUARTER, @DATA_DIMENSAO, @HOJE)))
/*SEMESTRE_REGRESSIVO*/							,rtrim(CONVERT(VARCHAR(10), @SEMESTRE_REG))
/*ANO_REGRESSIVO*/								,@ANO_REGRESSIVO
/*DIA_UTIL_REGRESSIVO*/							,@DIA_UTIL_REGRESSIVO
/*MES_UTIL_REGRESSIVO*/							,@MES_UTIL_REGRESSIVO
/*ANO_UTIL_REGRESSIVO*/							,@ANO_UTIL_REGRESSIVO
/*ULTIMOS_180_DIAS*/							,CASE WHEN DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE) >= 0 AND DATEDIFF(MONTH, @DATA_DIMENSAO, @HOJE) <=5 THEN 'S' ELSE 'N' END 
/*DATA_COMISSOES*/								,@DATA_COMISSOES
/*CALCULO_COMISSOES_REGRESSIVO*/				,@CALCULO_COMISSOES_REGRESSIVO+@CALCULO_COMISSOES_REGRESSIVO_DIF
/*DATA_COTAS*/									,@DATA_COTAS
/*COTAS_REGRESSIVO*/							,@DATA_COTAS_REGRESSIVO+@DATA_COTAS_REGRESSIVO_DIF
/*ID_DATA_MA*/									,CONVERT(VARCHAR(10), DATEADD(MONTH, -1, @DATA_DIMENSAO), 112)
/*ID_DATA_AA*/									,CONVERT(VARCHAR(10), DATEADD(YEAR, -1, @DATA_DIMENSAO), 112)
/*ID_DATA_AA_COMERCIAL*/						,0)
	     
	     
		  print @ANO_ANTERIOR
		  print DATEPART(YEAR, CONVERT(DATETIME,@DATA_DIMENSAO))
		  SET @ANO_ANTERIOR = DATEPART(YEAR, CONVERT(DATETIME,@DATA_DIMENSAO))

		  SET @DATA_DIMENSAO = DATEADD(DAY, 1, @DATA_DIMENSAO)
		  
		  IF(@CRIA_REGISTRO_1900 = 1)
			SET @CRIA_REGISTRO_1900 = 0
		  ELSE
			SET @CNT = @CNT + 1
		  
		  IF(DATEPART(MONTH, @MES_REGRESSIVO_DATA) <> DATEPART(MONTH, @DATA_DIMENSAO) 
				AND (@DIA_ATUAL_NUMERO = DATEPART(DAY, @DATA_DIMENSAO) 
						OR (DATEPART(DAY, @DATA_DIMENSAO) = 1 AND @DIA_ATUAL_NUMERO > DATEPART(DAY, DATEADD(month,DATEDIFF(month,0,DATEADD(MONTH, -1, @DATA_DIMENSAO))+1,-1)))))
		  BEGIN
				SET @MES_REGRESSIVO_ABRETO_DIF = @MES_REGRESSIVO_ABRETO_DIF -1
				SET @MES_REGRESSIVO_DATA = DATEADD(MONTH, -@MES_REGRESSIVO_ABRETO_DIF, @DATA_INI)
				
		  END 			

	  END
	  
	PRINT 'ATUALIZANDO CAMPOS QUEBRA MES/NULL - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	
	DECLARE @ID_DATA INT
	DECLARE @NUMERO_SEMANAS_QUEBRA_MES INT
	DECLARE @SEMANA_QUEBRA_MES_ANTERIOR VARCHAR(40) = NULL
	DECLARE @SEMANA_QUEBRA_MES_ATUAL VARCHAR(40) = NULL
	
	SELECT @NUMERO_SEMANAS_QUEBRA_MES = COUNT(DISTINCT SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA) 
	FROM #DIM_DATA_TEMP 
	WHERE DIA_REGRESSIVO >= 0/*+1 POR CAUSA QUE A VARIAVEL DE SEMANA ATUAL COMEÇA COMO NULL*/
	
	DECLARE C_SEMANAS_QUEBRA_MES CURSOR FOR 
	SELECT ID_DATA, SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA FROM #DIM_DATA_TEMP ORDER BY ID_DATA
	
	OPEN C_SEMANAS_QUEBRA_MES
	FETCH NEXT FROM C_SEMANAS_QUEBRA_MES 
	INTO @ID_DATA, @SEMANA_QUEBRA_MES_ANTERIOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
	
		IF(@SEMANA_QUEBRA_MES_ANTERIOR <> @SEMANA_QUEBRA_MES_ATUAL)
		BEGIN
			SET @NUMERO_SEMANAS_QUEBRA_MES = @NUMERO_SEMANAS_QUEBRA_MES - 1

			UPDATE #DIM_DATA_TEMP SET SEMANA_SEG_DOM_QUEBRA_MES_REGRESSIVA = @NUMERO_SEMANAS_QUEBRA_MES WHERE SEMANA_SEG_DOM_QUEBRA_MES_EXTENSA = @SEMANA_QUEBRA_MES_ANTERIOR
			
			SET @SEMANA_QUEBRA_MES_ANTERIOR = @SEMANA_QUEBRA_MES_ATUAL
		END
		
		FETCH NEXT FROM C_SEMANAS_QUEBRA_MES 
		INTO @ID_DATA, @SEMANA_QUEBRA_MES_ATUAL
	END

	CLOSE C_SEMANAS_QUEBRA_MES;
	DEALLOCATE C_SEMANAS_QUEBRA_MES;  
	   
	PRINT 'ATUALIZANDO CAMPOS COMERCIAIS - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)

	/*
	UPDATE #DIM_DATA_TEMP SET SEMANA_ANO_COMERCIAL = ISNULL((SELECT MAX(SEMANA_ANO_COMERCIAL) FROM #DIM_DATA_TEMP XXX WHERE (#DIM_DATA_TEMP.ANO-1) = XXX.ANO),0)
	WHERE SEMANA_ANO_COMERCIAL = 0 
	*/

	UPDATE D2 SET ID_DATA_AA_COMERCIAL = D.ID_DATA
	FROM 
		#DIM_DATA_TEMP D, 
		#DIM_DATA_TEMP D2
	 WHERE D.SEMANA_MES = D2.SEMANA_MES
	   AND D.MES = D2.MES
	   AND D.ANO = D2.ANO - 1
	   AND (D2.MES <> 2 AND D2.DIA_MES <> 29)
	   AND D.DIA_SEMANA = D2.DIA_SEMANA

	DECLARE C_DIAS_SEM_AA_COMERCIAL CURSOR FOR 
	SELECT ID_DATA FROM #DIM_DATA_TEMP D
	WHERE ID_DATA_AA_COMERCIAL = 0 
	  AND NOT EXISTS (SELECT 1 FROM #DIM_DATA_TEMP X WHERE X.MES = 2 AND X.DIA_MES = 29 AND X.ID_DATA = D.ID_DATA)
	
	OPEN C_DIAS_SEM_AA_COMERCIAL
	FETCH NEXT FROM C_DIAS_SEM_AA_COMERCIAL 
	INTO @ID_DATA

	WHILE @@FETCH_STATUS = 0
	BEGIN
	  
		  UPDATE D2 SET ID_DATA_AA_COMERCIAL = D.ID_DATA
		  FROM 
			#DIM_DATA_TEMP D,
			#DIM_DATA_TEMP D2
		 WHERE NOT EXISTS (SELECT 1 FROM #DIM_DATA_TEMP A WHERE A.ID_DATA_AA_COMERCIAL = D.ID_DATA)
		   AND D2.ANO-1 = D.ANO
		   AND D2.MES = D.MES
		   AND D2.ID_DATA = @ID_DATA

		FETCH NEXT FROM C_DIAS_SEM_AA_COMERCIAL 
		INTO @ID_DATA
	END

	CLOSE C_DIAS_SEM_AA_COMERCIAL;
	DEALLOCATE C_DIAS_SEM_AA_COMERCIAL;  

	UPDATE D2 SET ID_DATA_AA_COMERCIAL = D.ID_DATA
	FROM 
		#DIM_DATA_TEMP D, 
		#DIM_DATA_TEMP D2
	 WHERE D2.DIA_MES = 29
	   AND D.DIA_MES = 28
	   AND D2.MES = 2
	   AND D.MES = D2.MES
	   AND D.ANO = D2.ANO - 1
   


   UPDATE 
		#DIM_DATA_TEMP
	SET 
		ANO_COMERCIAL = 99999,
		MES_COMERCIAL = 99999,
		MES_COMERCIAL_NUMERICO = 99999,
		SEMANA_COMERCIAL = '99999',
		SEMANA_COMERCIAL_REMANEJO = '99999',
		SEMANA_COMERCIAL_REMANEJO_QUA_TER = '99999',
		SEMANA_COMERCIAL_NUMERICA = 99999,
		TRIMESTRE_COMERCIAL_NUMERICO = 99999,
		TRIMESTRE_COMERCIAL = '99999',
		TRIMESTRE_COMERCIAL_REGRESSIVO = 99999

	UPDATE 
		#DIM_DATA_TEMP
	SET 
		ANO_COMERCIAL = X.ANO_COMERCIAL,
		MES_COMERCIAL = X.MES_COMERCIAL,
		MES_COMERCIAL_NUMERICO = RIGHT(X.MES_COMERCIAL, 2),
		SEMANA_COMERCIAL = 'W'+CONVERT(VARCHAR,X.SEMANA_ANO)+' '+CONVERT(VARCHAR,X.ANO_COMERCIAL),
		SEMANA_COMERCIAL_REMANEJO = 'W'+CONVERT(VARCHAR,X.SEMANA_ANO)+' '+CONVERT(VARCHAR,X.ANO_COMERCIAL),
		SEMANA_COMERCIAL_REMANEJO_QUA_TER = 'W'+CONVERT(VARCHAR,X.SEMANA_ANO)+' '+CONVERT(VARCHAR,X.ANO_COMERCIAL),
		SEMANA_COMERCIAL_NUMERICA = X.SEMANA_ANO,
		TRIMESTRE_COMERCIAL_NUMERICO = X.TRIMESTRE_ANO
	FROM SEMANA_PERIODO_COMERCIAL X
	WHERE X.DATA_INICIAL <=  #DIM_DATA_TEMP.DATA_FILTRO
	  AND X.DATA_FINAL >= #DIM_DATA_TEMP.DATA_FILTRO
	

	UPDATE 
		#DIM_DATA_TEMP
	SET 
		MES_ANO_COMERCIAL = Y.MES_EXTENSO+'/'+CAST(Y.ANO AS VARCHAR(4)),
		MES_ANO_MMMYY_COMERCIAL = SUBSTRING(Y.MES_EXTENSO, 1,3)+'/'+CAST(Y.ANO AS VARCHAR(4)),
		MES_COMERCIAL_EXTENSO = Y.MES_EXTENSO
	FROM
		(SELECT 
			MES, MES_EXTENSO, ANO
			FROM #DIM_DATA_TEMP 
		GROUP BY MES_EXTENSO, ANO, MES) Y
	WHERE #DIM_DATA_TEMP.MES_COMERCIAL_NUMERICO =  Y.MES
	  AND #DIM_DATA_TEMP.ANO_COMERCIAL =  Y.ANO

	UPDATE 
		#DIM_DATA_TEMP
	SET 
		MES_COMERCIAL_ORDENACAO = Y.ORDENACAO
	FROM
		(	SELECT 
			MES_COMERCIAL, row_number() OVER(order by MES_COMERCIAL) ORDENACAO
			FROM #DIM_DATA_TEMP 
			group by MES_COMERCIAL) Y
	WHERE #DIM_DATA_TEMP.MES_COMERCIAL =  Y.MES_COMERCIAL

	UPDATE 
		#DIM_DATA_TEMP
	SET 
		MES_COMERCIAL_REGRESSIVO = (select MES_COMERCIAL_ORDENACAO from #DIM_DATA_TEMP where DIA_REGRESSIVO = 0) - MES_COMERCIAL_ORDENACAO

	UPDATE 
		#DIM_DATA_TEMP
	SET 
		ANO_COMERCIAL_REGRESSIVO = (select ANO_COMERCIAL from #DIM_DATA_TEMP where DIA_REGRESSIVO = 0) - ANO_COMERCIAL
	
	UPDATE 
		#DIM_DATA_TEMP
	SET 
		SEMANA_COMERCIAL_REGRESSIVA = (select SEMANA_COMERCIAL_NUMERICA from #DIM_DATA_TEMP where DIA_REGRESSIVO = 0) - SEMANA_COMERCIAL_NUMERICA

	UPDATE 
		#DIM_DATA_TEMP 
	SET 
		SEMANA_COMERCIAL_REMANEJO = X.SEMANA_COMERCIAL_REMANEJO
	FROM (
	SELECT 
	D2.SEMANA_COMERCIAL SEMANA_COMERCIAL_REMANEJO,
	D1.SEMANA_SEX_QUI_REGRESSIVA
	FROM 
		#DIM_DATA_TEMP D1,
		#DIM_DATA_TEMP D2
	WHERE [dbo].[FUNC_CONVERTE_DATETIME_INT](DATEADD(DAY, -7, D2.DATA_FILTRO)) = D1.ID_DATA
	  AND D1.DIA_SEMANA = 6
	  AND D2.DIA_SEMANA = 6) X
	  WHERE X.SEMANA_SEX_QUI_REGRESSIVA = #DIM_DATA_TEMP.SEMANA_SEX_QUI_REGRESSIVA

	UPDATE 
		#DIM_DATA_TEMP 
	SET 
		SEMANA_COMERCIAL_REMANEJO_QUA_TER = X.SEMANA_COMERCIAL_REMANEJO_QUA_TER
	FROM (
	SELECT 
	D2.SEMANA_COMERCIAL SEMANA_COMERCIAL_REMANEJO_QUA_TER,
	D1.SEMANA_QUA_TER_REGRESSIVA
	FROM 
		#DIM_DATA_TEMP D1,
		#DIM_DATA_TEMP D2
	WHERE [dbo].[FUNC_CONVERTE_DATETIME_INT](DATEADD(DAY, -7, D2.DATA_FILTRO)) = D1.ID_DATA
	  AND D1.DIA_SEMANA = 4
	  AND D2.DIA_SEMANA = 4) X
	  WHERE X.SEMANA_QUA_TER_REGRESSIVA = #DIM_DATA_TEMP.SEMANA_QUA_TER_REGRESSIVA

	
	UPDATE 
		#DIM_DATA_TEMP 
	SET TRIMESTRE_COMERCIAL = '1º Trim (Mar/'+cast(ano as varchar(4))+' a Mai/'+cast(ano as varchar(4))+')'
	WHERE TRIMESTRE_COMERCIAL_NUMERICO = 1

	UPDATE 
		#DIM_DATA_TEMP 
	SET TRIMESTRE_COMERCIAL = '2º Trim (Jun/'+cast(ano as varchar(4))+' a Ago/'+cast(ano as varchar(4))+')'  
	WHERE TRIMESTRE_COMERCIAL_NUMERICO = 2

	UPDATE 
		#DIM_DATA_TEMP 
	SET 
		TRIMESTRE_COMERCIAL = '3º Trim (Set/'+cast(ano as varchar(4))+' a Nov/'+cast(ano as varchar(4))+')'
	WHERE TRIMESTRE_COMERCIAL_NUMERICO = 3

	UPDATE 
		#DIM_DATA_TEMP 
	SET 
		TRIMESTRE_COMERCIAL = CASE
								WHEN ANO = ANO_COMERCIAL THEN '4º Trim (Dez/'+cast(ANO_COMERCIAL as varchar(4))+' a Fev/'+cast(ano+1 as varchar(4))+')'
								ELSE '4º Trim (Dez/'+cast(ANO_COMERCIAL as varchar(4))+' a Fev/'+cast(ano as varchar(4))+')'
							  END 
	WHERE TRIMESTRE_COMERCIAL_NUMERICO = 4
	

	UPDATE 
		#DIM_DATA_TEMP 
	SET 
		TRIMESTRE_COMERCIAL_REGRESSIVO = X.TRIMESTRE_COMERCIAL_REGRESSIVO
	FROM 
	(
		SELECT 
			ANO_COMERCIAL,
			trimestre_comercial_numerico, 
			max(id_data) ID_DATA_MAX, 
			min(id_data) ID_DATA_MIN, 
			(row_number() over(order by max(id_data) desc)-1) TRIMESTRE_COMERCIAL_REGRESSIVO
		FROM #DIM_DATA_TEMP
		where dia_regressivo >= 0
		  and trimestre_comercial_numerico <> 99999
		group by ANO_COMERCIAL, trimestre_comercial_numerico
	) X
	WHERE #DIM_DATA_TEMP.ID_DATA <= X.ID_DATA_MAX
	  AND #DIM_DATA_TEMP.ID_DATA >= X.ID_DATA_MIN


		UPDATE 
		#DIM_DATA_TEMP 
	SET 
		TRIMESTRE_COMERCIAL_REGRESSIVO = X.TRIMESTRE_COMERCIAL_REGRESSIVO
	FROM 
	(
		SELECT 
			ANO_COMERCIAL,
			trimestre_comercial_numerico, 
			max(id_data) ID_DATA_MAX, 
			min(id_data) ID_DATA_MIN, 
			(row_number() over(order by max(id_data))-1)*(-1) TRIMESTRE_COMERCIAL_REGRESSIVO
		FROM #DIM_DATA_TEMP
		where dia_regressivo <= 0
		  and trimestre_comercial_numerico <> 99999
		group by ANO_COMERCIAL, trimestre_comercial_numerico
	) X
	WHERE #DIM_DATA_TEMP.ID_DATA <= X.ID_DATA_MAX
	  AND #DIM_DATA_TEMP.ID_DATA >= X.ID_DATA_MIN


	IF((SELECT max(SEMANA_COMERCIAL_NUMERICA) FROM  #DIM_DATA_TEMP WHERE ANO_COMERCIAL_REGRESSIVO = 0 AND MES_COMERCIAL_REGRESSIVO = 0 AND SEMANA_COMERCIAL_REGRESSIVA > 0) > 0)
	BEGIN
		UPDATE 
			#DIM_DATA_TEMP
		SET MES_COMERCIAL_REGRESSIVO_QUEBRA_ANO = 'S'
		WHERE SEMANA_COMERCIAL_NUMERICA IN (SELECT 
												SEMANA_COMERCIAL_NUMERICA 
											  FROM  #DIM_DATA_TEMP 
											  WHERE MES_COMERCIAL_REGRESSIVO = 0
												AND SEMANA_COMERCIAL_REGRESSIVA > 0)
	END
	ELSE
	BEGIN
	 /*VIROU O MES*/
	 UPDATE 
			#DIM_DATA_TEMP
		SET MES_COMERCIAL_REGRESSIVO_QUEBRA_ANO = 'S'
		WHERE SEMANA_COMERCIAL_NUMERICA IN (SELECT 
												SEMANA_COMERCIAL_NUMERICA 
											  FROM  #DIM_DATA_TEMP 
											  WHERE MES_COMERCIAL_REGRESSIVO = 1
												AND SEMANA_COMERCIAL_REGRESSIVA > 0)
	END
	



	PRINT 'FIM DO PROCESSAMENTO - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	
	PRINT 'DELETANDO TABELA '+ @DBNAME +'.'+ @TABELA +' - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	EXEC('IF OBJECT_ID(''' + @DBNAME +'.'+ @TABELA +''') IS NOT NULL DROP TABLE '+ @DBNAME +'.'+ @TABELA)
	
	PRINT 'INSERINDO DADOS NA TABELA '+ @DBNAME +'.'+ @TABELA +' - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	
	DECLARE @COMANDO VARCHAR(4000) = 'SELECT * INTO ' + @DBNAME +'.'+ @TABELA +' FROM #DIM_DATA_TEMP WHERE ID_DATA = ' + CAST(@REGISTRO_1900 AS VARCHAR(10)) + ' OR ID_DATA >= ' + @DATA_INI_ORIGINAL_STRING
	PRINT @COMANDO
	EXEC(@COMANDO)

	EXEC('ALTER TABLE '+ @DBNAME +'.'+ @TABELA +' ADD PRIMARY KEY (ID_DATA)') 
	
	PRINT 'FIM DE EXECUCAO DA PROCEDURE - ' + CONVERT(VARCHAR(8),@HOJE,108) + ' - '+ CONVERT(VARCHAR(8),@HOJE,103)
	
END

GO
